/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;
import java.util.Random;
/**
 *
 * @author IsaacRL26
 */
public class interfaces extends javax.swing.JFrame {

    /**
     * Creates new form interfaces
     */
    public interfaces() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonExit = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jLabelAM = new javax.swing.JLabel();
        jLabelAP = new javax.swing.JLabel();
        jLabelDIA = new javax.swing.JLabel();
        jLabelMES = new javax.swing.JLabel();
        jLabelANO = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldAMT = new javax.swing.JTextField();
        jTextFieldAPT = new javax.swing.JTextField();
        jTextFieldDIA = new javax.swing.JTextField();
        jTextFieldMES = new javax.swing.JTextField();
        jTextFieldANO = new javax.swing.JTextField();
        jButtonGenerarRFC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldgRFCGEN = new javax.swing.JTextField();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonExit.setBackground(new java.awt.Color(51, 0, 102));
        jButtonExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 80, 30));

        jLabelNombre.setBackground(new java.awt.Color(51, 0, 102));
        jLabelNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("NOMBRE:");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabelAM.setBackground(new java.awt.Color(102, 0, 102));
        jLabelAM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelAM.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAM.setText("APELLIDO MATERNO:");
        getContentPane().add(jLabelAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabelAP.setBackground(new java.awt.Color(51, 0, 102));
        jLabelAP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelAP.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAP.setText("APELLIDO PATERNO:");
        getContentPane().add(jLabelAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabelDIA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDIA.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDIA.setText("DIA:");
        getContentPane().add(jLabelDIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        jLabelMES.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelMES.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMES.setText("MES:");
        getContentPane().add(jLabelMES, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        jLabelANO.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelANO.setForeground(new java.awt.Color(255, 255, 255));
        jLabelANO.setText("AÑO:");
        getContentPane().add(jLabelANO, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        jTextFieldNom.setBackground(new java.awt.Color(51, 0, 102));
        jTextFieldNom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldNom.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 160, -1));

        jTextFieldAMT.setBackground(new java.awt.Color(51, 0, 102));
        jTextFieldAMT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldAMT.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldAMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAMTActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldAMT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 160, -1));

        jTextFieldAPT.setBackground(new java.awt.Color(51, 0, 102));
        jTextFieldAPT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldAPT.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldAPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 160, -1));

        jTextFieldDIA.setBackground(new java.awt.Color(51, 0, 102));
        jTextFieldDIA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldDIA.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldDIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 70, -1));

        jTextFieldMES.setBackground(new java.awt.Color(51, 0, 102));
        jTextFieldMES.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldMES.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldMES, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 70, -1));

        jTextFieldANO.setBackground(new java.awt.Color(51, 0, 102));
        jTextFieldANO.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldANO.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldANO, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 70, -1));

        jButtonGenerarRFC.setBackground(new java.awt.Color(51, 0, 102));
        jButtonGenerarRFC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonGenerarRFC.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGenerarRFC.setText("GENERAR RFC");
        jButtonGenerarRFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarRFCActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGenerarRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 170, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RFC:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, -1, -1));

        jTextFieldgRFCGEN.setBackground(new java.awt.Color(51, 0, 102));
        jTextFieldgRFCGEN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextFieldgRFCGEN.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldgRFCGEN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextFieldgRFCGEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 200, 40));

        jLabelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/desktop-wallpaper-xperia-z-ultra-tornasol.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 754, 482));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
     System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jTextFieldAMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAMTActionPerformed
        // TODO add rfyour handling code here:
    }//GEN-LAST:event_jTextFieldAMTActionPerformed

    private void jTextFieldNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomActionPerformed

    private void jButtonGenerarRFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarRFCActionPerformed
    String alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        Random r = new Random();
        char let = alphabet.charAt(r.nextInt(alphabet.length()));
        //codigo para generar numero aleatorio de 10 a 99
    Random numAleatorio = new Random();
    
        int n = numAleatorio.nextInt(99-10+1) + 10;
        jTextFieldgRFCGEN.setText(jLabelAP.getText().substring(0,2)
        +jTextFieldAMT.getText().substring(0,1)
        +jTextFieldNom.getText().substring(0,1)
        +jTextFieldANO.getText().substring(2,4)
        +jTextFieldMES.getText().substring(0,2)
        +jTextFieldDIA.getText().substring(0,2)+let+n);
    }//GEN-LAST:event_jButtonGenerarRFCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaces().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonGenerarRFC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAM;
    private javax.swing.JLabel jLabelANO;
    private javax.swing.JLabel jLabelAP;
    private javax.swing.JLabel jLabelDIA;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelMES;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JTextField jTextFieldAMT;
    private javax.swing.JTextField jTextFieldANO;
    private javax.swing.JTextField jTextFieldAPT;
    private javax.swing.JTextField jTextFieldDIA;
    private javax.swing.JTextField jTextFieldMES;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldgRFCGEN;
    // End of variables declaration//GEN-END:variables
}
